import { Dumbbell, Gift, Trophy, UtensilsCrossed, Wrench } from "lucide-react";

export const BIRTHDAY_CONFETTI_DOTS = [
  { size: "h-3 w-3", color: "bg-primary", top: "8%", left: "3%", rotate: "rotate-12" },
  { size: "h-2 w-2", color: "bg-secondary", top: "15%", left: "12%", rotate: "-rotate-6" },
  { size: "h-4 w-2", color: "bg-primary/60", top: "5%", left: "30%", rotate: "rotate-45" },
  { size: "h-2 w-4", color: "bg-secondary/70", top: "20%", left: "55%", rotate: "-rotate-12" },
  { size: "h-3 w-3", color: "bg-primary", top: "10%", left: "72%", rotate: "rotate-6" },
  { size: "h-2 w-2", color: "bg-secondary", top: "6%", left: "88%", rotate: "rotate-45" },
  { size: "h-4 w-2", color: "bg-primary/50", top: "75%", left: "6%", rotate: "-rotate-45" },
  { size: "h-2 w-3", color: "bg-secondary/60", top: "85%", left: "20%", rotate: "rotate-12" },
  { size: "h-3 w-2", color: "bg-primary", top: "90%", left: "45%", rotate: "-rotate-6" },
  { size: "h-2 w-2", color: "bg-secondary", top: "80%", left: "65%", rotate: "rotate-45" },
  { size: "h-4 w-3", color: "bg-primary/60", top: "70%", left: "80%", rotate: "-rotate-12" },
  { size: "h-2 w-2", color: "bg-secondary/80", top: "88%", left: "93%", rotate: "rotate-6" },
  { size: "h-2 w-4", color: "bg-primary", top: "35%", left: "1%", rotate: "rotate-12" },
  { size: "h-3 w-2", color: "bg-secondary/70", top: "50%", left: "8%", rotate: "-rotate-45" },
  { size: "h-2 w-2", color: "bg-primary/70", top: "60%", left: "15%", rotate: "rotate-6" },
  { size: "h-4 w-2", color: "bg-secondary", top: "42%", left: "22%", rotate: "-rotate-12" },
  { size: "h-2 w-3", color: "bg-primary/80", top: "30%", left: "38%", rotate: "rotate-45" },
  { size: "h-3 w-3", color: "bg-secondary/50", top: "55%", left: "48%", rotate: "-rotate-6" },
  { size: "h-2 w-2", color: "bg-primary", top: "38%", left: "60%", rotate: "rotate-12" },
  { size: "h-4 w-2", color: "bg-secondary/60", top: "65%", left: "68%", rotate: "-rotate-45" },
  { size: "h-2 w-3", color: "bg-primary/60", top: "45%", left: "78%", rotate: "rotate-6" },
  { size: "h-3 w-2", color: "bg-secondary", top: "25%", left: "85%", rotate: "-rotate-12" },
  { size: "h-2 w-2", color: "bg-primary/80", top: "52%", left: "95%", rotate: "rotate-45" },
  { size: "h-4 w-3", color: "bg-secondary/70", top: "18%", left: "43%", rotate: "-rotate-6" },
  { size: "h-2 w-2", color: "bg-primary", top: "72%", left: "35%", rotate: "rotate-12" },
  { size: "h-3 w-4", color: "bg-secondary/50", top: "95%", left: "75%", rotate: "-rotate-45" },
  { size: "h-2 w-2", color: "bg-primary/70", top: "3%", left: "62%", rotate: "rotate-6" },
  { size: "h-3 w-2", color: "bg-secondary", top: "97%", left: "10%", rotate: "-rotate-12" },
  { size: "h-2 w-3", color: "bg-primary/80", top: "12%", left: "50%", rotate: "rotate-6" },
  { size: "h-3 w-2", color: "bg-secondary/60", top: "28%", left: "70%", rotate: "-rotate-45" },
  { size: "h-2 w-2", color: "bg-primary", top: "44%", left: "90%", rotate: "rotate-12" },
  { size: "h-4 w-2", color: "bg-secondary/70", top: "62%", left: "57%", rotate: "-rotate-6" },
  { size: "h-2 w-4", color: "bg-primary/60", top: "33%", left: "17%", rotate: "rotate-45" },
  { size: "h-3 w-3", color: "bg-secondary", top: "78%", left: "42%", rotate: "-rotate-12" },
  { size: "h-2 w-2", color: "bg-primary/70", top: "16%", left: "95%", rotate: "rotate-6" },
  { size: "h-4 w-3", color: "bg-secondary/50", top: "57%", left: "28%", rotate: "-rotate-45" },
  { size: "h-2 w-3", color: "bg-primary", top: "83%", left: "87%", rotate: "rotate-12" },
  { size: "h-3 w-2", color: "bg-secondary/80", top: "22%", left: "33%", rotate: "-rotate-6" },
  { size: "h-2 w-2", color: "bg-primary/50", top: "68%", left: "5%", rotate: "rotate-45" },
  { size: "h-4 w-2", color: "bg-secondary", top: "47%", left: "52%", rotate: "-rotate-12" },
  { size: "h-2 w-4", color: "bg-primary/80", top: "91%", left: "30%", rotate: "rotate-6" },
  { size: "h-3 w-3", color: "bg-secondary/60", top: "7%", left: "77%", rotate: "-rotate-45" },
  { size: "h-2 w-2", color: "bg-primary", top: "74%", left: "18%", rotate: "rotate-12" },
  { size: "h-3 w-2", color: "bg-secondary/70", top: "40%", left: "98%", rotate: "-rotate-6" },
  { size: "h-2 w-3", color: "bg-primary/60", top: "19%", left: "25%", rotate: "rotate-45" },
  { size: "h-4 w-2", color: "bg-secondary", top: "86%", left: "60%", rotate: "-rotate-12" },
  { size: "h-2 w-2", color: "bg-primary/70", top: "53%", left: "83%", rotate: "rotate-6" },
  { size: "h-3 w-4", color: "bg-secondary/50", top: "31%", left: "45%", rotate: "-rotate-45" },
];

export const BIRTHDAY_ACTIVITIES = [
  { icon: Gift, label: "pierwsze darmowe wejście do klubu" },
  { icon: Dumbbell, label: "wyjątkowe zajęcia fitness" },
  { icon: Wrench, label: "warsztaty" },
  { icon: UtensilsCrossed, label: "poczęstunek" },
  { icon: Trophy, label: "konkursy z nagrodami" },
];

export const BIRTHDAY_PROMOTIONS = [
  { highlight: "10% rabatu", text: "na suplementy" },
  { highlight: "10% rabatu", text: "na karnety opłacane z góry" },
  { highlight: "przy umowie na 12 miesięcy", text: "– dodatkowy miesiąc gratis" },
  { highlight: "przy umowie na 6 miesięcy", text: "– dodatkowe 3 tygodnie gratis" },
  { highlight: "przy umowie na 3 miesiące", text: "– dodatkowe 2 tygodnie gratis" },
];
